server:
  port: 8080
spring:
  application:
    name: FilmApp
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
    url: jdbc:mysql://localhost:3306/filmapp?createDatabaseIfNotExist=true

  #Keycloak
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:8181/realms/filmApp"


# Configura SpringDoc para que el tipo de contenido predeterminado de las respuestas API sea 'application/json'.
# Esto hace que en la especificación de OpenApi generada, se indique que el tipo de respuesta para todos los endpoints será de tipo JSON.
# Sin esto, cuando la dependencia open-api-gen genere los métodos para consumir los endpoints, tratarán a la respuesta como BLOB por defecto en lugar de JSON
springdoc:
  default-produces-media-type: application/json